use_frameworks!

platform :ios, '10.0'
install!'cocoapods', :warn_for_unused_master_specs_repo => false

target 'VVSequelize_Example' do
  pod 'VVSequelize', :path => '../'

  target 'VVSequelize_Tests' do
    inherit! :search_paths
  end
end
